post http://localhost:4000/postinfo/newpost
Content-Type: application/json

{
    "username":"ravi234",
    "profileIcon":"imagenotthere",
    "designation":"full stack developer",
    "description":{
        "text":"i dont no why i am doing",
        "images":[],
        "videos":"",
        "linkProject":"",
        "likes":"",
        "comments":[]
    }
}
###

post http://localhost:4000/projectinfo/newproject
Content-Type: application/json

{    
    "projectId": "2024-03-23T11:50:00.006Z",
    "username": "web_developer",
    "projectName": "Blog Platform",
    "description": "A platform for sharing content and stories",
    "status": true,
    "private": false
,

    "branches":[{}],
    "mentor":"",
    "Files":[
        {
            "nameOfFile":"",
            "data":""
        }
    ]

    
}

###
post http://localhost:4000/tutorials/newtutorial


###
get http://localhost:4000/usersinfo/userproject/ravi234

###
get http://localhost:4000/projectinfo/getprojects
